### ISSUE TITLE
Open source this ANE?

### ISSUE THREAD

**Issue by Oldes** [airsdk/ANE-PlayAssetDelivery#13]
Maybe it would be more educative to have real ANE's sources and not just the binary ANE itself, wouldn't it?

**Comment by PippoApps** [comment]
Maybe also the SWC to ease development.

**Comment by ajwfrost** [comment]
I can put in a request for open sourcing stuff, we have some internal admin/processes to go through for that.

The .ane file should be usable just the same as a .swc file though, I thought?

**Comment by Oldes** [comment]
@ajwfrost any news on it? I am just trying the ANE now and it seems not to be able initialize itself. As there is only release build where are no log messages, maybe you could provide at least a debug version for now?

**Comment by ajwfrost** [comment]
Hi @Oldes  - we've just been updating this ANE, so are about to release a version that allows a debug flag to be set.. the open-sourcing discussion didn't go anywhere but things have changed more recently so will have another go at that.

Pre-release of the new ANE version is in this zip:
[PlayAssetDelivery.zip](https://github.com/airsdk/ANE-PlayAssetDelivery/files/13940467/PlayAssetDelivery.zip)
There's a new property `debugMode` on the ANE, so if you create the `PlayAssetDelivery` object, try immediately setting this flag before calling the `initAssetDelivery` function.

@PippoApps from the above comment, I hadn't realised that you couldn't use the ANE in the same way as a SWC file when using Ant, have created an update there: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1443#discussioncomment-7464212 which went into 50.2.3.8. So hopefully now, the ANE is fine and you don't need a separate SWC..

thanks

**Comment by ajwfrost** [comment]
Hi

An exception throwing out of the ANE isn't so good .. but if there is a problem in initialization, it may be because of a dependency? I'll see if there's some better debugging/error messaging that we can put in place here...

Are you able to check the below post to ensure you've got the manifest additions plus dependent library in there?
https://github.com/airsdk/ANE-PlayAssetDelivery/issues/7#issuecomment-1025253478

thanks

**Comment by Oldes** [comment]
Where one can find the mentioned `com.google.android.play` extension?

**Comment by ajwfrost** [comment]
Should be this one:
https://github.com/distriqt/ANE-GooglePlayServices/blob/master/lib/com.google.android.play.ane
I think we may need to update our documentation, I couldn't see these instructions in our wiki!

**Comment by Oldes** [comment]
I can confirm that the ANE works fine with the manifest additions and the `com.google.android.play` ANE.

**Comment by ajwfrost** [comment]
Thanks! Have just updated the wiki page:
https://github.com/airsdk/ANE-PlayAssetDelivery/wiki#configure-the-application

**Comment by Oldes** [comment]
@ajwfrost anyway... I still believe that this ANE should be open source. There are still undocumented parts... for example:
`getByteDownloaded` and `getTotalBytesToDownLoad`... (btw.. it would be good to have these 2 names using same style!)

**Comment by Oldes** [comment]
I just released my open sourced version which we use in our projects now ->> https://github.com/Oldes/ANE_GooglePlayAssets

It is missing features we don't need (`install-time` assets support) but including features missing in the Harman's extension (exception handling - like when user want to fetch a pack and don't have network connection or enough space on the device)
