### ISSUE TITLE
Missing PlayAssetDeliveryEvent Class

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/ANE-PlayAssetDelivery#2]
Hi, I find the `PlayAssetDeliveryEvent` Class is missing.
Another thing is that could you please provide a demo project so that we could follow it. I don't see an example for on-depand / fast-follow on the wiki page. As debugging is so difficult, I'm a bit lost here... Thanks again for your help!

**Comment by marchbold** [comment]
I've updated the apm package to include the new release and should be available now. Not sure why it wasn't pushed out originally, will double check the release process on this extension. 

Let me know if you have any issues with the update.

**Comment by jimmymjing** [comment]
Thanks so much. Now it is included in!
